FROM mcr.microsoft.com/windows/node:20-windowsservercore-ltsc2019
WORKDIR /app

# Configura npm
RUN npm config set strict-ssl false

# Instala Angular CLI globalmente
RUN npm install -g @angular/cli

# Copia e instala dependencias
COPY package*.json ./
RUN npm install

# Copia el resto del código
COPY . .

EXPOSE 4200 

CMD ["cmd", "/c", "ng serve --host 0.0.0.0 --port 4200 --disable-host-check"]
